server:
  port: "8080"
logger:
  level: "debug"
  filePath: "logs/gateway.log"
routing:
  rules:
    "/api/v1/user":
      - target: "http://localhost:8081"
        weight: 4
      - target: "http://localhost:8083"
        weight: 2
    "/api/v1/order":
      - target: "http://localhost:8082"
        weight: 1
  engine: "gin"
  loadBalancer: "round_robin"
security:
  authMode: "rbac"
  jwt:
    secret: "change-to-your-secret-key"
    expiresIn: 7200000
    enabled: true
  rbac:
    enabled: true
    modelPath: "config/data/rbac_model.conf"
    policyPath: "config/data/rbac_policy.csv"
  ipBlacklist:
    - "192.168.1.100"
  ipWhitelist:
    - "127.0.0.1"
traffic:
  rateLimit:
    enabled: true
    qps: 1000
    burst: 2000
  breaker:
    enabled: true
    errorRate: 0.5
    timeout: 10
observability:
  prometheus:
    enabled: true
    path: "/metrics"
plugins:
  - "log"
  - "metrics"