server:
  port: "8080"
logger:
  level: "debug"
  filePath: "logs/gateway.log"
middleware:
  rateLimit: true
  ipAcl: true
  antiInjection: true
  auth: true
  breaker: true
routing:
  rules:
    "/api/v1/user":
      - target: "http://localhost:8081"
        weight: 4
      - target: "http://localhost:8083"
        weight: 2
    "/api/v1/order":
      - target: "http://localhost:8082"
        weight: 1
  engine: "gin"
  loadBalancer: "round_robin"
security:
  authMode: "jwt"
  jwt:
    secret: "change-to-your-secret-key"
    expiresIn: 7200000
    enabled: true
  rbac:
    enabled: true
    modelPath: "config/data/rbac_model.conf"
    policyPath: "config/data/rbac_policy.csv"
  ipBlacklist:
    - "192.168.1.100"
  ipWhitelist:
    - "127.0.0.1"
  ipUpdateMode: "override" # 可选值：override（覆盖）或 append（追加）
cache:
  addr: "10.2.103.35:6379"
  password: ""
  db: 0
traffic:
  rateLimit:
    enabled: true
    qps: 1500
    burst: 3000
    algorithm: "leaky_bucket"  # 可选值: "token_bucket" 或 "leaky_bucket"
  breaker:
    enabled: true
    errorRate: 0.5
    timeout: 1000
    minRequests: 20
    sleepWindow: 5000
    maxConcurrent: 100
    windowSize: 100
    windowDuration: 10
observability:
  prometheus:
    enabled: true
    path: "/metrics"
plugins:
  - "log"
  - "metrics"